import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./../public/css/custom-bootstrap.scss";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const StoreProvider = dynamic(() => import("@/lib/redux/StoreProvider"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
